spring:
  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: phi
        options:
          temperature: 0.2
          num-predict: 256

      embedding:
        model: nomic-embed-text


logging:
  level:
    root: INFO
    com.zeeshan.ai: DEBUG
    org.springframework.ai: INFO
